# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurnate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.DateTimeField(db_index=True)),
                ('dueño', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='restaurantesimgs')),
                ('direccion', models.TextField()),
            ],
        ),
    ]
